-- SiBantu V2 — skema awal Supabase
-- Jalankan melalui Supabase SQL Editor pada fase koneksi database.

create extension if not exists pgcrypto;

create type public.user_role as enum ('customer', 'admin', 'courier');
create type public.order_status as enum ('pending', 'confirmed', 'preparing', 'delivering', 'completed', 'cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'customer',
  full_name text,
  phone text,
  created_at timestamptz not null default now()
);

create table public.guest_sessions (
  id uuid primary key default gen_random_uuid(),
  public_token uuid not null default gen_random_uuid() unique,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  emoji text,
  sort_order int not null default 0,
  is_active boolean not null default true
);

create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id),
  name text not null,
  description text,
  emoji text,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  label text not null,
  unit text not null,
  unit_amount numeric(12,3) not null default 1,
  price numeric(14,2) not null check (price >= 0),
  stock numeric(14,3) not null default 0,
  sku text unique,
  is_default boolean not null default false,
  is_active boolean not null default true
);

create table public.product_aliases (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  alias text not null,
  unique(product_id, alias)
);

create table public.carts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.profiles(id),
  guest_session_id uuid references public.guest_sessions(id),
  status text not null default 'active' check (status in ('active','converted','abandoned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (customer_id is not null or guest_session_id is not null)
);

create unique index one_active_customer_cart on public.carts(customer_id) where status = 'active' and customer_id is not null;
create unique index one_active_guest_cart on public.carts(guest_session_id) where status = 'active' and guest_session_id is not null;

create table public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.carts(id) on delete cascade,
  variant_id bigint not null references public.product_variants(id),
  quantity numeric(12,3) not null check (quantity > 0),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(cart_id, variant_id)
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.profiles(id),
  guest_session_id uuid references public.guest_sessions(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (customer_id is not null or guest_session_id is not null)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user','assistant','tool')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.profiles(id),
  guest_session_id uuid references public.guest_sessions(id),
  recipient_name text not null,
  phone text not null,
  address_text text not null,
  landmark text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now(),
  check (customer_id is not null or guest_session_id is not null)
);

create table public.delivery_zones (
  id bigint generated by default as identity primary key,
  name text not null,
  fee numeric(14,2) not null default 0,
  min_order numeric(14,2) not null default 0,
  max_distance_km numeric(8,2),
  is_active boolean not null default true
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_id uuid references public.profiles(id),
  guest_session_id uuid references public.guest_sessions(id),
  address_id uuid not null references public.addresses(id),
  status public.order_status not null default 'pending',
  subtotal numeric(14,2) not null,
  delivery_fee numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  total numeric(14,2) not null,
  payment_method text not null default 'cod',
  customer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (customer_id is not null or guest_session_id is not null)
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_name text not null,
  variant_label text not null,
  unit_price numeric(14,2) not null,
  quantity numeric(12,3) not null,
  line_total numeric(14,2) not null,
  note text
);

create table public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  status public.order_status not null,
  note text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.promotions (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  discount_type text not null check (discount_type in ('fixed','percent')),
  discount_value numeric(14,2) not null,
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default true
);

alter table public.profiles enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;

create policy "users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "customers read own carts" on public.carts for select using (auth.uid() = customer_id);
create policy "customers read own conversations" on public.conversations for select using (auth.uid() = customer_id);
create policy "customers read own addresses" on public.addresses for select using (auth.uid() = customer_id);
create policy "customers read own orders" on public.orders for select using (auth.uid() = customer_id);

-- Guest checkout akan diakses melalui Route Handler server dengan service role.
-- Jangan pernah mengekspos SUPABASE_SERVICE_ROLE_KEY ke browser.
