-- SiBantu V2 — skema awal Supabase
-- Jalankan melalui Supabase SQL Editor pada fase koneksi database.

create extension if not exists pgcrypto;

create type public.user_role as enum ('customer', 'seller', 'admin', 'courier');
create type public.store_status as enum ('pending', 'active', 'suspended', 'rejected');
create type public.order_status as enum ('pending', 'confirmed', 'preparing', 'delivering', 'completed', 'cancelled');
create type public.payout_status as enum ('pending', 'processing', 'paid', 'failed');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.user_role not null default 'customer',
  full_name text,
  phone text,
  created_at timestamptz not null default now()
);

create table public.guest_sessions (
  id uuid primary key default gen_random_uuid(),
  public_token uuid not null default gen_random_uuid() unique,
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table public.stores (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid references public.profiles(id) on delete cascade,
  is_platform_store boolean not null default false,
  name text not null,
  slug text not null unique,
  description text,
  phone text not null,
  whatsapp text,
  address_text text not null,
  latitude double precision,
  longitude double precision,
  status public.store_status not null default 'pending',
  commission_rate numeric(5,2) not null default 5.00 check (commission_rate between 0 and 100),
  logo_url text,
  banner_url text,
  opening_hours jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (owner_id is not null or is_platform_store = true)
);

create table public.seller_applications (
  id uuid primary key default gen_random_uuid(),
  applicant_id uuid not null references public.profiles(id) on delete cascade,
  store_id uuid references public.stores(id) on delete cascade,
  identity_name text not null,
  identity_number text,
  business_type text,
  document_urls jsonb not null default '[]'::jsonb,
  status public.store_status not null default 'pending',
  review_note text,
  reviewed_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table public.store_members (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  member_role text not null default 'staff' check (member_role in ('owner','manager','staff')),
  created_at timestamptz not null default now(),
  unique(store_id, profile_id)
);

create table public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  emoji text,
  sort_order int not null default 0,
  is_active boolean not null default true
);

create table public.products (
  id bigint generated by default as identity primary key,
  store_id uuid not null references public.stores(id) on delete cascade,
  category_id bigint references public.categories(id),
  name text not null,
  description text,
  emoji text,
  image_url text,
  moderation_status text not null default 'pending' check (moderation_status in ('pending','approved','rejected')),
  moderation_note text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  label text not null,
  unit text not null,
  unit_amount numeric(12,3) not null default 1,
  price numeric(14,2) not null check (price >= 0),
  stock numeric(14,3) not null default 0,
  sku text unique,
  is_default boolean not null default false,
  is_active boolean not null default true
);

create table public.product_aliases (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  alias text not null,
  unique(product_id, alias)
);

create table public.carts (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.profiles(id),
  guest_session_id uuid references public.guest_sessions(id),
  status text not null default 'active' check (status in ('active','converted','abandoned')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (customer_id is not null or guest_session_id is not null)
);

create unique index one_active_customer_cart on public.carts(customer_id) where status = 'active' and customer_id is not null;
create unique index one_active_guest_cart on public.carts(guest_session_id) where status = 'active' and guest_session_id is not null;

create table public.cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.carts(id) on delete cascade,
  variant_id bigint not null references public.product_variants(id),
  quantity numeric(12,3) not null check (quantity > 0),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(cart_id, variant_id)
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.profiles(id),
  guest_session_id uuid references public.guest_sessions(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (customer_id is not null or guest_session_id is not null)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user','assistant','tool')),
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.profiles(id),
  guest_session_id uuid references public.guest_sessions(id),
  recipient_name text not null,
  phone text not null,
  address_text text not null,
  landmark text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now(),
  check (customer_id is not null or guest_session_id is not null)
);

create table public.delivery_zones (
  id bigint generated by default as identity primary key,
  name text not null,
  fee numeric(14,2) not null default 0,
  min_order numeric(14,2) not null default 0,
  max_distance_km numeric(8,2),
  is_active boolean not null default true
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique,
  customer_id uuid references public.profiles(id),
  guest_session_id uuid references public.guest_sessions(id),
  address_id uuid not null references public.addresses(id),
  status public.order_status not null default 'pending',
  subtotal numeric(14,2) not null,
  delivery_fee numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  total numeric(14,2) not null,
  payment_method text not null default 'cod',
  customer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (customer_id is not null or guest_session_id is not null)
);

create table public.store_orders (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  store_id uuid not null references public.stores(id),
  status public.order_status not null default 'pending',
  items_subtotal numeric(14,2) not null,
  platform_fee numeric(14,2) not null default 0,
  seller_net numeric(14,2) not null,
  seller_note text,
  accepted_at timestamptz,
  prepared_at timestamptz,
  created_at timestamptz not null default now(),
  unique(order_id, store_id)
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  store_order_id uuid not null references public.store_orders(id) on delete cascade,
  store_id uuid not null references public.stores(id),
  product_name text not null,
  variant_label text not null,
  unit_price numeric(14,2) not null,
  quantity numeric(12,3) not null,
  line_total numeric(14,2) not null,
  note text
);

create table public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  status public.order_status not null,
  note text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

create table public.seller_payouts (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id),
  period_start date not null,
  period_end date not null,
  gross_sales numeric(14,2) not null default 0,
  platform_fee numeric(14,2) not null default 0,
  adjustments numeric(14,2) not null default 0,
  payout_amount numeric(14,2) not null,
  status public.payout_status not null default 'pending',
  payout_reference text,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.store_reviews (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  order_id uuid not null references public.orders(id) on delete cascade,
  customer_id uuid references public.profiles(id),
  rating int not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  unique(store_id, order_id)
);

create table public.promotions (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  discount_type text not null check (discount_type in ('fixed','percent')),
  discount_value numeric(14,2) not null,
  starts_at timestamptz,
  ends_at timestamptz,
  is_active boolean not null default true
);

alter table public.profiles enable row level security;
alter table public.stores enable row level security;
alter table public.seller_applications enable row level security;
alter table public.store_members enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.carts enable row level security;
alter table public.cart_items enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.addresses enable row level security;
alter table public.orders enable row level security;
alter table public.store_orders enable row level security;
alter table public.seller_payouts enable row level security;
alter table public.store_reviews enable row level security;

create policy "users read own profile" on public.profiles for select using (auth.uid() = id);
create policy "users update own profile" on public.profiles for update using (auth.uid() = id);
create policy "customers read own carts" on public.carts for select using (auth.uid() = customer_id);
create policy "customers read own conversations" on public.conversations for select using (auth.uid() = customer_id);
create policy "customers read own addresses" on public.addresses for select using (auth.uid() = customer_id);
create policy "customers read own orders" on public.orders for select using (auth.uid() = customer_id);

create policy "public reads active stores" on public.stores for select using (status = 'active');
create policy "sellers read own stores" on public.stores for select using (auth.uid() = owner_id);
create policy "sellers update own stores" on public.stores for update using (auth.uid() = owner_id);
create policy "users submit seller applications" on public.seller_applications for insert with check (auth.uid() = applicant_id);
create policy "users read own seller applications" on public.seller_applications for select using (auth.uid() = applicant_id);
create policy "members read own membership" on public.store_members for select using (auth.uid() = profile_id);

create policy "public reads approved products" on public.products for select using (
  is_active = true and moderation_status = 'approved'
);
create policy "sellers create products in own store" on public.products for insert with check (
  exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid())
);
create policy "sellers update products in own store" on public.products for update using (
  exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid())
);
create policy "public reads active variants" on public.product_variants for select using (
  is_active = true and exists (
    select 1 from public.products p where p.id = product_id and p.is_active = true and p.moderation_status = 'approved'
  )
);
create policy "sellers manage variants in own store" on public.product_variants for all using (
  exists (
    select 1 from public.products p
    join public.stores s on s.id = p.store_id
    where p.id = product_id and s.owner_id = auth.uid()
  )
);
create policy "sellers read own store orders" on public.store_orders for select using (
  exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid())
);
create policy "sellers update own store orders" on public.store_orders for update using (
  exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid())
);
create policy "sellers read own payouts" on public.seller_payouts for select using (
  exists (select 1 from public.stores s where s.id = store_id and s.owner_id = auth.uid())
);
create policy "customers create store reviews" on public.store_reviews for insert with check (auth.uid() = customer_id);
create policy "public reads store reviews" on public.store_reviews for select using (true);

-- Guest checkout akan diakses melalui Route Handler server dengan service role.
-- Jangan pernah mengekspos SUPABASE_SERVICE_ROLE_KEY ke browser.
