'use client';

import { FormEvent, useEffect, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/client';
import { rupiah } from '@/lib/format';

type Profile={id:string;full_name?:string;phone?:string;avatar_url?:string;marketing_consent:boolean};
type Address={id:string;recipient_name:string;phone:string;address_text:string;landmark?:string;latitude?:number;longitude?:number};
type Order={id:string;order_number:string;status:string;total:number;created_at:string;order_items?:{product_name:string;variant_label:string;quantity:number;line_total:number}[]};
type Notification={id:string;title:string;body:string;link_url?:string;read_at?:string;created_at:string};

export default function CustomerDashboard(){
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[email,setEmail]=useState('');const [profile,setProfile]=useState<Profile|null>(null),[roles,setRoles]=useState<string[]>([]),[addresses,setAddresses]=useState<Address[]>([]),[orders,setOrders]=useState<Order[]>([]),[notifications,setNotifications]=useState<Notification[]>([]),[tab,setTab]=useState<'overview'|'orders'|'addresses'|'notifications'>('overview');const [addressForm,setAddressForm]=useState({recipient_name:'',phone:'',address_text:'',landmark:''});
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setError('');try{const supabase=getBrowserSupabase();const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.href='/akun/login';return;}setEmail(session.user.email||'');const [{data:p},{data:r},{data:a},{data:o},{data:n}]=await Promise.all([supabase.from('profiles').select('id,full_name,phone,avatar_url,marketing_consent').eq('id',session.user.id).single(),supabase.from('account_roles').select('role').eq('profile_id',session.user.id),supabase.from('addresses').select('id,recipient_name,phone,address_text,landmark,latitude,longitude').eq('customer_id',session.user.id).order('created_at',{ascending:false}),supabase.from('orders').select('id,order_number,status,total,created_at,order_items(product_name,variant_label,quantity,line_total)').eq('customer_id',session.user.id).order('created_at',{ascending:false}),supabase.from('notifications').select('id,title,body,link_url,read_at,created_at').eq('profile_id',session.user.id).order('created_at',{ascending:false}).limit(50)]);setProfile(p);setRoles((r||[]).map(x=>x.role));setAddresses(a||[]);setOrders(o||[]);setNotifications(n||[]);setAddressForm(v=>({...v,recipient_name:p?.full_name||'',phone:p?.phone||''}));}catch(reason){setError(reason instanceof Error?reason.message:'Akun gagal dimuat.')}finally{setLoading(false)}}
 async function updateProfile(event:FormEvent){event.preventDefault();if(!profile)return;setSaving(true);setError('');try{const supabase=getBrowserSupabase();const {error:e}=await supabase.from('profiles').update({full_name:profile.full_name,phone:profile.phone,updated_at:new Date().toISOString()}).eq('id',profile.id);if(e)throw e;setNotice('Profil berhasil disimpan.');}catch(reason){setError(reason instanceof Error?reason.message:'Profil gagal disimpan.')}finally{setSaving(false)}}
 async function addAddress(event:FormEvent){event.preventDefault();if(!profile)return;setSaving(true);setError('');try{const {error:e}=await getBrowserSupabase().from('addresses').insert({customer_id:profile.id,...addressForm});if(e)throw e;setAddressForm({...addressForm,address_text:'',landmark:''});setNotice('Alamat berhasil ditambahkan.');await load();}catch(reason){setError(reason instanceof Error?reason.message:'Alamat gagal disimpan.')}finally{setSaving(false)}}
 async function deleteAddress(id:string){if(!confirm('Hapus alamat ini?'))return;await getBrowserSupabase().from('addresses').delete().eq('id',id);await load()}
 async function toggleMarketing(subscribed:boolean){if(!profile)return;setSaving(true);setError('');try{const {error:e}=await getBrowserSupabase().rpc('set_marketing_consent',{p_channel:'email',p_subscribed:subscribed,p_destination:email});if(e)throw e;setProfile({...profile,marketing_consent:subscribed});setNotice(subscribed?'Promo email diaktifkan.':'Promo email dihentikan.');}catch(reason){setError(reason instanceof Error?reason.message:'Preferensi gagal diubah.')}finally{setSaving(false)}}
 async function logout(){await getBrowserSupabase().auth.signOut();window.location.href='/'}
 if(loading)return <div className="account-loading">Memuat akun...</div>;if(!profile)return <div className="account-loading">Profil tidak ditemukan.</div>;
 return <main className="account-dashboard"><header><div><small>AKUN SIBANTU</small><h1>Halo, {profile.full_name||'Pembeli'}</h1><p>{email}</p></div><button onClick={logout}>Keluar</button></header>{error&&<div className="account-alert error">{error}</div>}{notice&&<div className="account-alert success">{notice}</div>}
 <section className="role-switcher"><b>Pilih mode</b><a className="active" href="/akun/dashboard">🛍️ Pembeli</a>{roles.includes('seller')&&<a href="/mitra/dashboard">🏪 Mitra</a>}{roles.includes('admin')&&<a href="/admin/mitra">🛡️ Admin</a>}</section>
 <nav className="account-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Ringkasan</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Pesanan ({orders.length})</button><button className={tab==='addresses'?'active':''} onClick={()=>setTab('addresses')}>Alamat ({addresses.length})</button><button className={tab==='notifications'?'active':''} onClick={()=>setTab('notifications')}>Notifikasi ({notifications.length})</button></nav>
 {tab==='overview'&&<div className="account-columns"><form onSubmit={updateProfile} className="profile-card"><h2>Profil</h2><label>Nama<input value={profile.full_name||''} onChange={e=>setProfile({...profile,full_name:e.target.value})}/></label><label>WhatsApp<input value={profile.phone||''} onChange={e=>setProfile({...profile,phone:e.target.value})}/></label><button disabled={saving}>Simpan profil</button></form><section className="consent-card"><h2>Promo & hadiah</h2><p>Promo hanya dikirim jika kamu setuju. Bisa dihentikan kapan saja.</p><label><input type="checkbox" checked={profile.marketing_consent} onChange={e=>void toggleMarketing(e.target.checked)}/><span>Terima promo melalui email</span></label></section><section className="account-stats"><article><b>{orders.length}</b><span>Total order</span></article><article><b>{addresses.length}</b><span>Alamat tersimpan</span></article><article><b>{notifications.filter(n=>!n.read_at).length}</b><span>Belum dibaca</span></article></section></div>}
 {tab==='orders'&&<section className="account-list">{!orders.length&&<div className="account-empty">Belum ada order akun. Order guest sebelumnya belum ditautkan.</div>}{orders.map(order=><article key={order.id}><header><b>{order.order_number}</b><mark className={`status-${order.status}`}>{order.status}</mark></header><small>{new Date(order.created_at).toLocaleString('id-ID')}</small><ul>{order.order_items?.map((item,index)=><li key={index}>{item.product_name} — {item.quantity} {item.variant_label} — {rupiah(item.line_total)}</li>)}</ul><footer>Total <b>{rupiah(order.total)}</b></footer></article>)}</section>}
 {tab==='addresses'&&<div className="address-layout"><form onSubmit={addAddress}><h2>Tambah alamat</h2><label>Penerima<input value={addressForm.recipient_name} onChange={e=>setAddressForm({...addressForm,recipient_name:e.target.value})}/></label><label>WhatsApp<input value={addressForm.phone} onChange={e=>setAddressForm({...addressForm,phone:e.target.value})}/></label><label>Alamat<textarea value={addressForm.address_text} onChange={e=>setAddressForm({...addressForm,address_text:e.target.value})}/></label><label>Patokan<input value={addressForm.landmark} onChange={e=>setAddressForm({...addressForm,landmark:e.target.value})}/></label><button disabled={saving}>Simpan alamat</button></form><section className="saved-addresses">{addresses.map(address=><article key={address.id}><b>{address.recipient_name}</b><span>{address.phone}</span><p>{address.address_text}<br/>{address.landmark}</p><button onClick={()=>void deleteAddress(address.id)}>Hapus</button></article>)}</section></div>}
 {tab==='notifications'&&<section className="notification-list">{!notifications.length&&<div className="account-empty">Belum ada notifikasi.</div>}{notifications.map(item=><article className={item.read_at?'':'unread'} key={item.id}><b>{item.title}</b><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString('id-ID')}</small></article>)}</section>}
 </main>
}
