'use client';

import { FormEvent, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/client';

export default function CustomerRegistration(){
 const [form,setForm]=useState({name:'',phone:'',email:'',password:'',marketing:false});const [loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 async function submit(event:FormEvent){event.preventDefault();setError('');setMessage('');if(form.name.trim().length<2||form.phone.replace(/\D/g,'').length<10||form.password.length<8){setError('Lengkapi nama, WhatsApp, dan password minimal 8 karakter.');return;}setLoading(true);try{const supabase=getBrowserSupabase();const {data,error:signError}=await supabase.auth.signUp({email:form.email.trim(),password:form.password,options:{emailRedirectTo:`${window.location.origin}/akun/dashboard`,data:{full_name:form.name.trim(),phone:form.phone.trim()}}});if(signError)throw signError;if(data.session&&data.user){if(form.marketing)await supabase.rpc('set_marketing_consent',{p_channel:'email',p_subscribed:true,p_destination:form.email.trim()});window.location.href='/akun/dashboard';}else{localStorage.setItem('sibantu_customer_marketing',form.marketing?'1':'0');setMessage('Akun dibuat. Buka email verifikasi, lalu login ke SiBantu.');}}catch(reason){setError(reason instanceof Error?reason.message:'Pendaftaran gagal.');}finally{setLoading(false)}}
 return <form className="account-card" onSubmit={submit}><div className="account-icon">👤</div><h1>Daftar Pembeli</h1><p>Simpan alamat, riwayat order, dan dapatkan pengalaman belanja lebih cepat.</p><label>Nama lengkap<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Nomor WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} inputMode="tel" placeholder="08xxxxxxxxxx"/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></label><label>Password<input type="password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label className="consent"><input type="checkbox" checked={form.marketing} onChange={e=>setForm({...form,marketing:e.target.checked})}/><span>Saya bersedia menerima promo melalui email. Saya dapat berhenti kapan saja.</span></label>{error&&<div className="account-alert error">{error}</div>}{message&&<div className="account-alert success">{message}</div>}<button disabled={loading}>{loading?'Membuat akun...':'Daftar akun pembeli'}</button><a href="/akun/login">Sudah punya akun? Masuk</a></form>
}
