import { NextRequest, NextResponse } from 'next/server';
import { authenticateRequest } from '@/lib/supabase/auth-server';

function text(value: unknown, max=500){return String(value??'').trim().slice(0,max)}

export async function GET(request:NextRequest){const auth=await authenticateRequest(request);if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});const {data,error}=await auth.supabase.from('stores').select('id,name,slug,description,phone,whatsapp,address_text,latitude,longitude,status,logo_url,banner_url,opening_hours,min_order,preparation_minutes,delivery_area_text,is_accepting_orders,temporary_close_reason,vacation_until,order_cutoff_time,commission_rate').eq('owner_id',auth.user.id).limit(1).maybeSingle();if(error)return NextResponse.json({error:error.message},{status:500});if(!data)return NextResponse.json({error:'Toko tidak ditemukan.'},{status:404});return NextResponse.json({ok:true,store:data})}

export async function PATCH(request:NextRequest){const auth=await authenticateRequest(request);if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});const {data:current}=await auth.supabase.from('stores').select('id,status').eq('owner_id',auth.user.id).limit(1).maybeSingle();if(!current)return NextResponse.json({error:'Toko tidak ditemukan.'},{status:404});const body=await request.json();
 const name=text(body.name,120),description=text(body.description,1000),phone=text(body.phone,30),whatsapp=text(body.whatsapp,30),address=text(body.address_text,500),deliveryArea=text(body.delivery_area_text,300),closeReason=text(body.temporary_close_reason,300);const minOrder=Number(body.min_order),preparation=Number(body.preparation_minutes);const base=process.env.NEXT_PUBLIC_SUPABASE_URL;const assetPrefix=`${base}/storage/v1/object/public/store-assets/`;const logo=text(body.logo_url,1000),banner=text(body.banner_url,1000);if((logo&&!logo.startsWith(assetPrefix))||(banner&&!banner.startsWith(assetPrefix)))return NextResponse.json({error:'URL logo/banner tidak valid.'},{status:400});if(name.length<2||phone.replace(/\D/g,'').length<10||address.length<8||!Number.isFinite(minOrder)||minOrder<0||!Number.isFinite(preparation)||preparation<5||preparation>1440)return NextResponse.json({error:'Data toko belum valid.'},{status:400});
 const openingHours=typeof body.opening_hours==='object'&&body.opening_hours?body.opening_hours:{};const update={name,description,phone,whatsapp:whatsapp||phone,address_text:address,delivery_area_text:deliveryArea||null,min_order:minOrder,preparation_minutes:preparation,is_accepting_orders:Boolean(body.is_accepting_orders),temporary_close_reason:body.is_accepting_orders?null:(closeReason||'Toko tutup sementara'),vacation_until:body.vacation_until||null,order_cutoff_time:body.order_cutoff_time||null,opening_hours:openingHours,logo_url:logo||null,banner_url:banner||null,updated_at:new Date().toISOString()};const {data,error}=await auth.supabase.from('stores').update(update).eq('id',current.id).eq('owner_id',auth.user.id).select('*').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,store:data})}
