'use client';

import { useEffect, useState } from 'react';
import { rupiah } from '@/lib/format';

type Store={id:string;name:string;slug:string;description?:string;phone:string;whatsapp:string;address_text:string;logo_url?:string;banner_url?:string;opening_hours:any;min_order:number;preparation_minutes:number;delivery_area_text?:string;is_accepting_orders:boolean;temporary_close_reason?:string;vacation_until?:string;averageRating:number;reviewCount:number};type Product={id:number;name:string;description:string;emoji:string;imageUrl?:string;unit:string;price:number;stock:number};
export default function PublicStorePage({slug}:{slug:string}){const [store,setStore]=useState<Store|null>(null),[products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{fetch(`/api/stores/${slug}`).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);setStore(data.store);setProducts(data.products)}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[slug]);if(loading)return<div className="public-store-loading">Memuat toko...</div>;if(error||!store)return<div className="public-store-loading">{error||'Toko tidak ditemukan.'}</div>;const vacation=store.vacation_until&&new Date(store.vacation_until)>new Date();const open=store.is_accepting_orders&&!vacation;
 return <main className="public-store"><header style={store.banner_url?{backgroundImage:`linear-gradient(#103f2c99,#103f2c99),url(${store.banner_url})`}:undefined}><a href="/">←</a><div className="public-store-profile">{store.logo_url?<img src={store.logo_url} alt={store.name}/>:<span>🏪</span>}<div><small>TOKO MITRA SIBANTU</small><h1>{store.name}</h1><p>⭐ {store.averageRating.toFixed(1)} ({store.reviewCount} ulasan)</p></div></div></header><section className={`store-open-status ${open?'open':'closed'}`}><b>{open?'● Toko buka':'● Toko tutup'}</b><span>{open?`Persiapan sekitar ${store.preparation_minutes} menit`:(store.temporary_close_reason||'Tutup sementara')}</span></section><section className="store-public-info"><p>{store.description}</p><div><span>📍 {store.address_text}</span><span>🛵 {store.delivery_area_text||'Area layanan belum diatur'}</span><span>🧺 Minimum {rupiah(store.min_order||0)}</span></div><a href={`https://wa.me/${String(store.whatsapp||store.phone).replace(/\D/g,'').replace(/^0/,'62')}`} target="_blank" rel="noreferrer">💬 Chat toko</a></section><div className="store-products-heading"><h2>Produk toko</h2><span>{products.length} produk</span></div><section className="store-product-grid">{products.map(product=><a href={`/?product=${product.id}`} key={product.id}><div>{product.imageUrl?<img src={product.imageUrl} alt={product.name}/>:<span>{product.emoji}</span>}{product.stock<=0&&<mark>Habis</mark>}</div><h3>{product.name}</h3><p>{rupiah(product.price)} <small>/ {product.unit}</small></p></a>)}</section></main>
}
