import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { ownedStore } from '@/lib/supabase/auth-server';

function maskAccount(value:string){const clean=String(value||'');return clean.length<=4?'••••':`${'•'.repeat(Math.min(8,clean.length-4))}${clean.slice(-4)}`}

export async function GET(request:NextRequest){const auth=await ownedStore(request);if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});const [ordersRes,payoutsRes,accountsRes]=await Promise.all([auth.supabase.from('store_orders').select('status,items_subtotal,platform_fee,seller_net,payout_id').eq('store_id',auth.store.id),auth.supabase.from('seller_payouts').select('id,gross_sales,platform_fee,adjustments,payout_amount,status,payout_reference,requested_at,paid_at,created_at,payment_account_id').eq('store_id',auth.store.id).order('created_at',{ascending:false}).limit(100),auth.supabase.from('seller_payment_accounts').select('id,account_type,provider_name,account_number,account_name,is_primary,verification_status,verification_note,created_at').eq('store_id',auth.store.id).order('created_at',{ascending:false})]);const orders=ordersRes.data||[];const available=orders.filter(o=>o.status==='completed'&&!o.payout_id).reduce((sum,o)=>sum+Number(o.seller_net||0),0);const processing=orders.filter(o=>!['completed','cancelled'].includes(o.status)).reduce((sum,o)=>sum+Number(o.seller_net||0),0);const paid=(payoutsRes.data||[]).filter(p=>p.status==='paid').reduce((sum,p)=>sum+Number(p.payout_amount||0),0);const commission=orders.filter(o=>o.status!=='cancelled').reduce((sum,o)=>sum+Number(o.platform_fee||0),0);const accounts=(accountsRes.data||[]).map(a=>({...a,account_number_masked:maskAccount(a.account_number),account_number:undefined}));return NextResponse.json({ok:true,store:auth.store,summary:{available,processing,paid,commission,minimumPayout:50000},accounts,payouts:payoutsRes.data||[]})}

export async function POST(request:NextRequest){const auth=await ownedStore(request);if(!auth.ok)return NextResponse.json({error:auth.error},{status:auth.status});const body=await request.json();const action=String(body.action||'');
 if(action==='add_account'){const type=String(body.accountType||''),provider=String(body.providerName||'').trim().slice(0,80),number=String(body.accountNumber||'').replace(/\s/g,'').slice(0,80),name=String(body.accountName||'').trim().slice(0,120);if(!['bank','ewallet'].includes(type)||provider.length<2||number.length<5||name.length<2)return NextResponse.json({error:'Data rekening belum lengkap.'},{status:400});const {data,error}=await auth.supabase.from('seller_payment_accounts').insert({store_id:auth.store.id,account_type:type,provider_name:provider,account_number:number,account_name:name,is_primary:Boolean(body.isPrimary),verification_status:'pending'}).select('id').single();if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true,accountId:data.id,status:'pending'})}
 if(action==='delete_account'){const id=String(body.accountId||'');const {error}=await auth.supabase.from('seller_payment_accounts').delete().eq('id',id).eq('store_id',auth.store.id).eq('verification_status','pending');if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}
 if(action==='request_payout'){const accountId=String(body.accountId||''),token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token)return NextResponse.json({error:'Login diperlukan.'},{status:401});const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;if(!url||!key)return NextResponse.json({error:'Supabase public config belum tersedia.'},{status:503});const userClient=createClient(url,key,{auth:{persistSession:false},global:{headers:{Authorization:`Bearer ${token}`}}});const {data,error}=await userClient.rpc('request_seller_payout',{p_store_id:auth.store.id,p_payment_account_id:accountId});if(error){const friendly=error.message.includes('PAYMENT_ACCOUNT_NOT_VERIFIED')?'Rekening belum diverifikasi owner.':error.message.includes('MINIMUM_PAYOUT_50000')?'Saldo tersedia belum mencapai Rp50.000.':error.message;return NextResponse.json({error:friendly},{status:409})}return NextResponse.json({ok:true,payoutId:data,status:'pending'})}
 return NextResponse.json({error:'Action tidak valid.'},{status:400})}
