'use client';

import { FormEvent, useEffect, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/client';
import { rupiah } from '@/lib/format';

type Application={id:string;status:string;store_name?:string;review_note?:string};
type Store={id:string;name:string;status:string;address_text:string};
type Product={id:number;name:string;emoji:string;moderation_status:string;moderation_note?:string;is_active:boolean;categories?:{slug:string;name:string};product_variants?:{id:number;label:string;unit:string;price:number;stock:number;is_default:boolean;is_active:boolean}[]};
type Order={id:string;status:string;items_subtotal:number;platform_fee:number;seller_net:number;created_at:string;orders?:{order_number:string;addresses?:{recipient_name:string;phone:string;address_text:string;landmark?:string}};order_items?:{product_name:string;variant_label:string;quantity:number;line_total:number;note?:string}[]};

const CATEGORIES=[['sayur','Sayur'],['ikan','Ikan'],['daging','Daging'],['sembako','Sembako'],['buah','Buah'],['bumbu','Bumbu'],['rumah','Kebutuhan Rumah']];

export default function SellerDashboard(){
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[name,setName]=useState('Mitra');const [application,setApplication]=useState<Application|null>(null),[store,setStore]=useState<Store|null>(null);const [tab,setTab]=useState<'overview'|'products'|'orders'>('overview');const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[revenue,setRevenue]=useState(0),[saving,setSaving]=useState(false),[orderDrafts,setOrderDrafts]=useState<Record<string,string>>({});
 const [form,setForm]=useState({name:'',description:'',emoji:'📦',category:'sayur',unit:'kg',label:'1 kg',price:'',stock:'',aliases:''});
 useEffect(()=>{void loadAccount()},[]);
 async function accessToken(){const {data}=await getBrowserSupabase().auth.getSession();if(!data.session){window.location.href='/mitra/login';throw new Error('Login diperlukan');}return data.session.access_token}
 async function api(path:string,init:RequestInit={}){const token=await accessToken();const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Permintaan gagal');return data}
 async function loadAccount(){setLoading(true);try{const supabase=getBrowserSupabase();const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.href='/mitra/login';return;}setName(session.user.user_metadata?.full_name||session.user.email||'Mitra');const [{data:apps},{data:stores}]=await Promise.all([supabase.from('seller_applications').select('id,status,store_name,review_note').eq('applicant_id',session.user.id).order('created_at',{ascending:false}).limit(1),supabase.from('stores').select('id,name,status,address_text').eq('owner_id',session.user.id).limit(1)]);setApplication(apps?.[0]||null);const activeStore=stores?.[0]||null;setStore(activeStore);if(activeStore)await Promise.all([loadProducts(),loadOrders()]);}catch(reason){setError(reason instanceof Error?reason.message:'Gagal memuat');}finally{setLoading(false)}}
 async function loadProducts(){try{const data=await api('/api/mitra/products');setProducts(data.products||[]);}catch(reason){setError(reason instanceof Error?reason.message:'Produk gagal dimuat')}}
 async function loadOrders(){try{const data=await api('/api/mitra/orders');const nextOrders=data.orders||[];setOrders(nextOrders);setRevenue(Number(data.completedRevenue||0));setOrderDrafts(Object.fromEntries(nextOrders.map((order:Order)=>[order.id,order.status])));}catch(reason){setError(reason instanceof Error?reason.message:'Order gagal dimuat')}}
 async function createProduct(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await api('/api/mitra/products',{method:'POST',body:JSON.stringify({...form,price:Number(form.price),stock:Number(form.stock),aliases:form.aliases.split(',').map(v=>v.trim()).filter(Boolean)})});setForm({...form,name:'',description:'',price:'',stock:'',aliases:''});await loadProducts();}catch(reason){setError(reason instanceof Error?reason.message:'Produk gagal dibuat')}finally{setSaving(false)}}
 async function updateProduct(product:Product){const variant=product.product_variants?.find(v=>v.is_default);if(!variant)return;setSaving(true);try{await api('/api/mitra/products',{method:'PATCH',body:JSON.stringify({productId:product.id,price:variant.price,stock:variant.stock,isActive:product.is_active})});await loadProducts();}catch(reason){setError(reason instanceof Error?reason.message:'Update gagal')}finally{setSaving(false)}}
 async function saveOrderStatus(order:Order){const status=orderDrafts[order.id]||order.status;if(status===order.status){setNotice('Tidak ada perubahan status.');return;}let reason='';if(status==='cancelled'){reason=window.prompt('Alasan pembatalan (wajib):','Order test / stok tidak tersedia')?.trim()||'';if(reason.length<4){setError('Pembatalan dibatalkan karena alasan belum diisi.');return;}if(!window.confirm(`Batalkan order ${order.orders?.order_number}?`))return;}setSaving(true);setError('');setNotice('');try{await api('/api/mitra/orders',{method:'PATCH',body:JSON.stringify({orderId:order.id,status,reason})});setNotice(`Status order ${order.orders?.order_number} berhasil menjadi ${status}.`);await loadOrders();}catch(reason){setError(reason instanceof Error?reason.message:'Status gagal diperbarui')}finally{setSaving(false)}}
 async function logout(){await getBrowserSupabase().auth.signOut();window.location.href='/mitra/login'}
 if(loading)return <div className="dashboard-loading">Memuat dashboard...</div>;
 if(!application&&!store)return <div className="seller-dashboard"><section className="empty-dashboard"><span>📝</span><h2>Belum ada pendaftaran toko</h2><a href="/mitra/daftar">Daftar toko</a></section></div>;
 if(application&&!store)return <div className="seller-dashboard"><section className="application-status"><span>⏳</span><div><small>STATUS PENDAFTARAN</small><h2>{application.status==='pending'?'Menunggu verifikasi':application.status}</h2><p>Toko: <b>{application.store_name}</b></p>{application.review_note&&<em>{application.review_note}</em>}</div></section></div>;
 return <div className="seller-dashboard"><header><div><small>SIBANTU MITRA</small><h1>{store?.name}</h1><p>Halo, {name}</p></div><button onClick={logout}>Keluar</button></header>{error&&<div className="form-alert error">{error}</div>}{notice&&<div className="form-alert success">{notice}</div>}<nav className="seller-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Ringkasan</button><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>Produk ({products.length})</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Pesanan ({orders.length})</button></nav>
 {tab==='overview'&&<><section className="store-summary"><div><small>TOKO AKTIF</small><h2>{store?.name}</h2><p>{store?.address_text}</p></div><span>{store?.status}</span></section><div className="metric-grid"><article><small>PRODUK</small><b>{products.length}</b><span>{products.filter(p=>p.moderation_status==='approved').length} disetujui</span></article><article><small>ORDER</small><b>{orders.length}</b><span>{orders.filter(o=>o.status==='pending').length} pending</span></article><article><small>PENDAPATAN SELESAI</small><b>{rupiah(revenue)}</b><span>Setelah komisi</span></article></div></>}
 {tab==='products'&&<section className="product-manager"><form onSubmit={createProduct}><h2>Tambah produk</h2><div className="seller-fields"><label>Nama<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Emoji<input value={form.emoji} onChange={e=>setForm({...form,emoji:e.target.value})}/></label><label>Kategori<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Satuan<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value,label:`1 ${e.target.value}`})}/></label><label>Harga<input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Stok<input type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label className="wide">Deskripsi<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Alias, pisahkan koma<input value={form.aliases} onChange={e=>setForm({...form,aliases:e.target.value})}/></label></div><button disabled={saving}>Kirim untuk moderasi</button></form><div className="seller-product-list">{products.map(product=>{const variant=product.product_variants?.find(v=>v.is_default);return <article key={product.id}><span>{product.emoji}</span><div><b>{product.name}</b><small>{variant?`${rupiah(variant.price)} / ${variant.unit} • stok ${variant.stock}`:'Varian belum ada'}</small><mark className={`status-${product.moderation_status}`}>{product.moderation_status}</mark></div>{variant&&<button disabled={saving} onClick={()=>void updateProduct(product)}>Simpan</button>}</article>})}</div></section>}
 {tab==='orders'&&<section className="seller-orders">{!orders.length&&<div className="admin-empty">Belum ada pesanan untuk toko ini.</div>}{orders.map(order=><article key={order.id}><header><div><small>{order.orders?.order_number}</small><b>{new Date(order.created_at).toLocaleString('id-ID')}</b></div><mark className={`status-${order.status}`}>{order.status}</mark></header><p>{order.orders?.addresses?.recipient_name} • {order.orders?.addresses?.phone}<br/>{order.orders?.addresses?.address_text}</p><ul>{order.order_items?.map((item,index)=><li key={index}>{item.product_name} — {item.quantity} {item.variant_label} — {rupiah(item.line_total)}{item.note?` • ${item.note}`:''}</li>)}</ul><footer><b>Net: {rupiah(order.seller_net)}</b><div className="status-editor"><select disabled={saving||['completed','cancelled'].includes(order.status)} value={orderDrafts[order.id]||order.status} onChange={e=>setOrderDrafts({...orderDrafts,[order.id]:e.target.value})}><option value={order.status}>{order.status}</option>{order.status==='pending'&&<><option value="confirmed">confirmed</option><option value="cancelled">cancelled</option></>}{order.status==='confirmed'&&<><option value="preparing">preparing</option><option value="cancelled">cancelled</option></>}{order.status==='preparing'&&<><option value="delivering">delivering</option><option value="cancelled">cancelled</option></>}{order.status==='delivering'&&<option value="completed">completed</option>}</select><button disabled={saving||orderDrafts[order.id]===order.status||['completed','cancelled'].includes(order.status)} onClick={()=>void saveOrderStatus(order)}>Simpan status</button></div></footer></article>)}</section>}
 </div>}
