'use client';

import { useEffect, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/client';

type Review={id:string;rating:number;comment?:string;sellerReply?:string;createdAt:string;buyerName:string;product?:{id:number;name:string;image_url?:string}};
export default function SellerReviews(){const [filter,setFilter]=useState('all'),[reviews,setReviews]=useState<Review[]>([]),[summary,setSummary]=useState({total:0,unreplied:0,low:0,average:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[replying,setReplying]=useState(''),[reply,setReply]=useState('');useEffect(()=>{void load()},[filter]);
 async function token(){const {data}=await getBrowserSupabase().auth.getSession();if(!data.session){location.href='/mitra/login?next=/mitra/ulasan';throw new Error('Login diperlukan')}return data.session.access_token}
 async function load(){setLoading(true);setError('');try{const response=await fetch(`/api/mitra/reviews?filter=${filter}`,{headers:{Authorization:`Bearer ${await token()}`}});const data=await response.json();if(!response.ok)throw new Error(data.error);setReviews(data.reviews||[]);setSummary(data.summary);}catch(reason){setError(reason instanceof Error?reason.message:'Gagal memuat')}finally{setLoading(false)}}
 async function submit(reviewId:string){setError('');try{const response=await fetch('/api/mitra/reviews',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({reviewId,reply})});const data=await response.json();if(!response.ok)throw new Error(data.error);setReplying('');setReply('');await load();}catch(reason){setError(reason instanceof Error?reason.message:'Balasan gagal')}}
 return <main className="seller-reviews-page"><header><a href="/mitra/dashboard">←</a><div><small>SELLER CENTER</small><h1>Ulasan Pembeli</h1></div></header><section className="review-summary"><article><b>⭐ {summary.average.toFixed(1)}</b><span>Rating rata-rata</span></article><article><b>{summary.total}</b><span>Total ulasan</span></article><article><b>{summary.unreplied}</b><span>Perlu dibalas</span></article><article><b>{summary.low}</b><span>Rating rendah</span></article></section><nav className="review-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Semua</button><button className={filter==='unreplied'?'active':''} onClick={()=>setFilter('unreplied')}>Belum dibalas</button><button className={filter==='low'?'active':''} onClick={()=>setFilter('low')}>Rating 1–2</button></nav>{error&&<div className="form-alert error">{error}</div>}{loading?<div className="dashboard-loading">Memuat ulasan...</div>:<section className="seller-review-list">{!reviews.length&&<div className="admin-empty">Belum ada ulasan pada filter ini.</div>}{reviews.map(item=><article key={item.id}><header>{item.product?.image_url?<img src={item.product.image_url} alt=""/>:<span>📦</span>}<div><b>{item.product?.name||'Produk'}</b><small>Oleh {item.buyerName} • {new Date(item.createdAt).toLocaleDateString('id-ID')}</small></div><mark>{'★'.repeat(item.rating)}{'☆'.repeat(5-item.rating)}</mark></header><p>{item.comment||'Pembeli memberi rating tanpa komentar.'}</p>{item.sellerReply?<div className="seller-reply"><b>Balasan toko</b><p>{item.sellerReply}</p></div>:replying===item.id?<div className="reply-form"><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Tulis balasan yang ramah..."/><div><button onClick={()=>setReplying('')}>Batal</button><button onClick={()=>void submit(item.id)}>Kirim balasan</button></div></div>:<button className="reply-button" onClick={()=>{setReplying(item.id);setReply('')}}>Balas ulasan</button>}</article>)}</section>}</main>
}
