'use client';

import { FormEvent, useEffect, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/client';
import { rupiah } from '@/lib/format';

type Application={id:string;status:string;store_name?:string;review_note?:string};
type Store={id:string;name:string;status:string;address_text:string};
type Product={id:number;name:string;description?:string;emoji:string;image_url?:string;product_media?:{id:string;media_type:'image'|'video';url:string;sort_order:number}[];product_aliases?:{alias:string}[];moderation_status:string;moderation_note?:string;is_active:boolean;categories?:{slug:string;name:string};product_variants?:{id:number;label:string;unit:string;price:number;stock:number;is_default:boolean;is_active:boolean}[]};
type Order={id:string;status:string;items_subtotal:number;platform_fee:number;seller_net:number;created_at:string;orders?:{order_number:string;addresses?:{recipient_name:string;phone:string;address_text:string;landmark?:string}};order_items?:{product_name:string;variant_label:string;quantity:number;line_total:number;note?:string}[]};

const CATEGORIES=[['sayur','Sayur'],['ikan','Ikan'],['daging','Daging'],['sembako','Sembako'],['buah','Buah'],['bumbu','Bumbu'],['rumah','Kebutuhan Rumah']];

export default function SellerDashboard(){
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[name,setName]=useState('Mitra');const [application,setApplication]=useState<Application|null>(null),[store,setStore]=useState<Store|null>(null);const [tab,setTab]=useState<'overview'|'products'|'orders'>('overview');const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<Order[]>([]),[revenue,setRevenue]=useState(0),[saving,setSaving]=useState(false);const [imageFiles,setImageFiles]=useState<File[]>([]),[imagePreviews,setImagePreviews]=useState<string[]>([]),[videoFile,setVideoFile]=useState<File|null>(null),[videoPreview,setVideoPreview]=useState(''),[mediaStatus,setMediaStatus]=useState(''),[mediaError,setMediaError]=useState('');const [editingProduct,setEditingProduct]=useState<Product|null>(null),[editImageFiles,setEditImageFiles]=useState<File[]>([]),[editImagePreviews,setEditImagePreviews]=useState<string[]>([]),[editVideoFile,setEditVideoFile]=useState<File|null>(null),[editVideoPreview,setEditVideoPreview]=useState('');
 const [form,setForm]=useState({name:'',description:'',emoji:'📦',category:'sayur',unit:'kg',label:'1 kg',price:'',stock:'',aliases:''});
 const [editForm,setEditForm]=useState({name:'',description:'',emoji:'📦',category:'sayur',unit:'kg',price:'',stock:'',aliases:'',isActive:true});
 useEffect(()=>{void loadAccount()},[]);
 async function accessToken(){const {data}=await getBrowserSupabase().auth.getSession();if(!data.session){window.location.href='/mitra/login';throw new Error('Login diperlukan');}return data.session.access_token}
 async function api(path:string,init:RequestInit={}){const token=await accessToken();const response=await fetch(path,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.error||'Permintaan gagal');return data}
 async function loadAccount(){setLoading(true);try{const supabase=getBrowserSupabase();const {data:{session}}=await supabase.auth.getSession();if(!session){window.location.href='/mitra/login';return;}setName(session.user.user_metadata?.full_name||session.user.email||'Mitra');const [{data:apps},{data:stores}]=await Promise.all([supabase.from('seller_applications').select('id,status,store_name,review_note').eq('applicant_id',session.user.id).order('created_at',{ascending:false}).limit(1),supabase.from('stores').select('id,name,status,address_text').eq('owner_id',session.user.id).limit(1)]);setApplication(apps?.[0]||null);const activeStore=stores?.[0]||null;setStore(activeStore);if(activeStore)await Promise.all([loadProducts(),loadOrders()]);}catch(reason){setError(reason instanceof Error?reason.message:'Gagal memuat');}finally{setLoading(false)}}
 async function loadProducts(){try{const data=await api('/api/mitra/products');setProducts(data.products||[]);}catch(reason){setError(reason instanceof Error?reason.message:'Produk gagal dimuat')}}
 async function loadOrders(){try{const data=await api('/api/mitra/orders');const nextOrders=data.orders||[];setOrders(nextOrders);setRevenue(Number(data.completedRevenue||0));}catch(reason){setError(reason instanceof Error?reason.message:'Order gagal dimuat')}}
 function chooseImages(files:FileList|null){setError('');setMediaError('');setMediaStatus('');const selected=Array.from(files||[]).slice(0,8);if(selected.some(file=>!file.type.startsWith('image/'))){setMediaError('Semua file foto harus berupa gambar.');return;}if(selected.some(file=>file.size>3*1024*1024)){setMediaError('Setiap foto maksimal 3 MB.');return;}imagePreviews.forEach(url=>URL.revokeObjectURL(url));setImageFiles(selected);setImagePreviews(selected.map(file=>URL.createObjectURL(file)));setMediaStatus(`${selected.length} foto siap diupload.`);}
 function chooseVideo(file:File|null){setError('');setMediaError('');setMediaStatus('');if(!file){setVideoFile(null);setVideoPreview('');return;}if(!['video/mp4','video/webm'].includes(file.type)){setMediaError(`Format video ${file.type||'tidak dikenal'} belum didukung. Gunakan MP4 atau WebM.`);return;}if(file.size>15*1024*1024){setMediaError(`Ukuran video ${(file.size/1024/1024).toFixed(1)} MB. Maksimal 15 MB.`);return;}if(videoPreview)URL.revokeObjectURL(videoPreview);setVideoFile(file);setVideoPreview(URL.createObjectURL(file));setMediaStatus(`Video ${file.name} (${(file.size/1024/1024).toFixed(1)} MB) siap diupload.`);}
 async function uploadMedia(bucket:string,file:File,userId:string,index:number){const supabase=getBrowserSupabase();const extension=(file.name.split('.').pop()||'bin').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`${userId}/${Date.now()}-${index}-${Math.random().toString(36).slice(2,8)}.${extension}`;const {error:uploadError}=await supabase.storage.from(bucket).upload(path,file,{cacheControl:'3600',upsert:false});if(uploadError)throw uploadError;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl;}
 async function createProduct(event:FormEvent){event.preventDefault();setError('');setNotice('');if(imageFiles.length<2){setError('Tambahkan minimal 2 foto produk agar dapat langsung tayang.');return;}setSaving(true);try{const supabase=getBrowserSupabase();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Login diperlukan.');setMediaStatus('Mengupload foto produk...');const imageUrls=await Promise.all(imageFiles.map((file,index)=>uploadMedia('product-images',file,user.id,index)));setMediaStatus(videoFile?'Foto selesai. Mengupload video...':'Foto selesai. Menyimpan produk...');const videoUrl=videoFile?await uploadMedia('product-videos',videoFile,user.id,99):'';
 const result=await api('/api/mitra/products',{method:'POST',body:JSON.stringify({...form,imageUrls,videoUrl,price:Number(form.price),stock:Number(form.stock),aliases:form.aliases.split(',').map(v=>v.trim()).filter(Boolean)})});if(videoFile&&!result.videoSaved)throw new Error('Video selesai diupload tetapi belum tercatat. Coba edit produk dan upload ulang.');setMediaStatus(`Berhasil: ${result.imageCount} foto${result.videoSaved?' + 1 video':''} tersimpan.`);setNotice(result.autoPublished?'Produk lolos validasi dan langsung tayang.':'Produk dikirim untuk pemeriksaan admin.');setForm({...form,name:'',description:'',price:'',stock:'',aliases:''});imagePreviews.forEach(url=>URL.revokeObjectURL(url));setImageFiles([]);setImagePreviews([]);setVideoFile(null);setVideoPreview('');await loadProducts();}catch(reason){const message=reason instanceof Error?reason.message:'Produk gagal dibuat';setError(message);setMediaError(message);setMediaStatus('')}finally{setSaving(false)}}
 function openEdit(product:Product){const variant=product.product_variants?.find(v=>v.is_default);setEditingProduct(product);setEditForm({name:product.name,description:product.description||'',emoji:product.emoji||'📦',category:product.categories?.slug||'sayur',unit:variant?.unit||'kg',price:String(variant?.price||0),stock:String(variant?.stock||0),aliases:(product.product_aliases||[]).map(item=>item.alias).join(', '),isActive:product.is_active});setEditImageFiles([]);setEditImagePreviews((product.product_media||[]).filter(item=>item.media_type==='image').sort((a,b)=>a.sort_order-b.sort_order).map(item=>item.url));setEditVideoFile(null);setEditVideoPreview((product.product_media||[]).find(item=>item.media_type==='video')?.url||'');}
 function chooseEditImages(files:FileList|null){const selected=Array.from(files||[]).slice(0,8);if(selected.some(file=>!file.type.startsWith('image/')||file.size>3*1024*1024)){setError('Foto harus berupa gambar dan maksimal 3 MB per file.');return;}setEditImageFiles(selected);setEditImagePreviews(selected.map(file=>URL.createObjectURL(file)));}
 function chooseEditVideo(file:File|null){if(!file){setEditVideoFile(null);return;}if(!['video/mp4','video/webm'].includes(file.type)||file.size>15*1024*1024){setError('Video harus MP4/WebM dan maksimal 15 MB.');return;}setEditVideoFile(file);setEditVideoPreview(URL.createObjectURL(file));}
 async function saveProductEdit(event:FormEvent){event.preventDefault();if(!editingProduct)return;setSaving(true);setError('');setNotice('');try{let imageUrls:string[]|undefined;let videoUrl:string|undefined;if(editImageFiles.length){if(editImageFiles.length<2)throw new Error('Pilih minimal 2 foto jika mengganti galeri.');const {data:{user}}=await getBrowserSupabase().auth.getUser();if(!user)throw new Error('Login diperlukan.');imageUrls=await Promise.all(editImageFiles.map((file,index)=>uploadMedia('product-images',file,user.id,index)));if(editVideoFile)videoUrl=await uploadMedia('product-videos',editVideoFile,user.id,99);else videoUrl=(editingProduct.product_media||[]).find(item=>item.media_type==='video')?.url||'';}else if(editVideoFile){const {data:{user}}=await getBrowserSupabase().auth.getUser();if(!user)throw new Error('Login diperlukan.');imageUrls=(editingProduct.product_media||[]).filter(item=>item.media_type==='image').map(item=>item.url);videoUrl=await uploadMedia('product-videos',editVideoFile,user.id,99);}
 const payload:any={productId:editingProduct.id,...editForm,price:Number(editForm.price),stock:Number(editForm.stock),aliases:editForm.aliases.split(',').map(value=>value.trim()).filter(Boolean)};if(imageUrls)payload.imageUrls=imageUrls;if(videoUrl!==undefined)payload.videoUrl=videoUrl;const result=await api('/api/mitra/products',{method:'PATCH',body:JSON.stringify(payload)});if(editVideoFile&&!result.videoSaved)throw new Error('Video belum tercatat setelah update.');setNotice(`${result.autoPublished?'Perubahan aktif.':'Menunggu pemeriksaan.'} ${result.imageCount} foto${result.videoSaved?' + video':''} tersimpan.`);setEditingProduct(null);await loadProducts();}catch(reason){setError(reason instanceof Error?reason.message:'Update gagal')}finally{setSaving(false)}}
 async function saveOrderStatus(order:Order,status:string){if(status===order.status)return;let reason='';if(status==='cancelled'){reason=window.prompt('Alasan pembatalan (wajib):','Stok tidak tersedia')?.trim()||'';if(reason.length<4){setError('Pembatalan dibatalkan karena alasan belum diisi.');return;}}const labels:Record<string,string>={confirmed:'Terima pesanan ini?',preparing:'Mulai menyiapkan pesanan?',delivering:'Tandai pesanan siap/sedang diantar?',completed:'Tandai pesanan sudah diterima pelanggan?',cancelled:'Batalkan pesanan ini?'};if(!window.confirm(labels[status]||'Simpan perubahan status?'))return;setSaving(true);setError('');setNotice('');try{const result=await api('/api/mitra/orders',{method:'PATCH',body:JSON.stringify({orderId:order.id,status,reason})});setNotice(`Status seller menjadi ${status}; status pembeli menjadi ${result.orderStatus}.`);await loadOrders();}catch(reason){setError(reason instanceof Error?reason.message:'Status gagal diperbarui')}finally{setSaving(false)}}
 async function logout(){await getBrowserSupabase().auth.signOut();window.location.href='/mitra/login'}
 if(loading)return <div className="dashboard-loading">Memuat dashboard...</div>;
 if(!application&&!store)return <div className="seller-dashboard"><section className="empty-dashboard"><span>📝</span><h2>Belum ada pendaftaran toko</h2><a href="/mitra/daftar">Daftar toko</a></section></div>;
 if(application&&!store)return <div className="seller-dashboard"><section className="application-status"><span>⏳</span><div><small>STATUS PENDAFTARAN</small><h2>{application.status==='pending'?'Menunggu verifikasi':application.status}</h2><p>Toko: <b>{application.store_name}</b></p>{application.review_note&&<em>{application.review_note}</em>}</div></section></div>;
 return <div className="seller-dashboard"><header><div><small>SIBANTU MITRA</small><h1>{store?.name}</h1><p>Halo, {name}</p></div><div className="seller-header-actions"><a href="/mitra/pengaturan">⚙ Pengaturan</a><button onClick={logout}>Keluar</button></div></header>{error&&<div className="form-alert error">{error}</div>}{notice&&<div className="form-alert success">{notice}</div>}<nav className="seller-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Ringkasan</button><button className={tab==='products'?'active':''} onClick={()=>setTab('products')}>Produk ({products.length})</button><button className={tab==='orders'?'active':''} onClick={()=>setTab('orders')}>Pesanan ({orders.length})</button></nav>
 {tab==='overview'&&<><section className="store-summary"><div><small>TOKO AKTIF</small><h2>{store?.name}</h2><p>{store?.address_text}</p></div><span>{store?.status}</span></section><section className="seller-tools"><button onClick={()=>setTab('products')}><span>📦</span><b>Produk</b><small>{products.length} produk</small></button><button onClick={()=>setTab('orders')}><span>🧾</span><b>Pesanan</b><small>{orders.filter(o=>['pending','confirmed','preparing'].includes(o.status)).length} perlu tindakan</small></button><a href="/mitra/performa"><span>📊</span><b>Performa</b><small>Lihat statistik</small></a><button disabled><span>💰</span><b>Keuangan</b><small>Segera hadir</small></button><a href="/mitra/ulasan"><span>⭐</span><b>Ulasan</b><small>Balas pembeli</small></a></section><div className="metric-grid"><article><small>PRODUK</small><b>{products.length}</b><span>{products.filter(p=>p.moderation_status==='approved').length} disetujui</span></article><article><small>ORDER</small><b>{orders.length}</b><span>{orders.filter(o=>o.status==='pending').length} pending</span></article><article><small>PENDAPATAN SELESAI</small><b>{rupiah(revenue)}</b><span>Setelah komisi</span></article></div></>}
 {tab==='products'&&<section className="product-manager"><form onSubmit={createProduct}><h2>Tambah produk</h2><label className="product-image-upload"><input type="file" accept="image/*" multiple onChange={e=>chooseImages(e.target.files)}/><span>📷</span><div><b>Tambahkan 2–8 foto produk</b><small>{imageFiles.length?`${imageFiles.length} foto dipilih`:'JPG/PNG/WebP, masing-masing maksimal 3 MB'}</small></div></label>{imagePreviews.length>0&&<div className="media-previews">{imagePreviews.map((url,index)=><img key={url} src={url} alt={`Preview ${index+1}`}/>)}</div>}<label className="product-video-upload"><input type="file" accept="video/mp4,video/webm" onChange={e=>chooseVideo(e.target.files?.[0]||null)}/><span>🎬</span><div><b>Video produk (opsional)</b><small>{videoFile?videoFile.name:'MP4/WebM, maksimal 15 MB'}</small></div></label>{videoPreview&&<video className="video-preview" src={videoPreview} controls/>}{mediaStatus&&<div className="media-status success">{mediaStatus}</div>}{mediaError&&<div className="media-status error">{mediaError}</div>}<div className="seller-fields"><label>Nama<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Emoji<input value={form.emoji} onChange={e=>setForm({...form,emoji:e.target.value})}/></label><label>Kategori<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{CATEGORIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Satuan<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value,label:`1 ${e.target.value}`})}/></label><label>Harga<input type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></label><label>Stok<input type="number" value={form.stock} onChange={e=>setForm({...form,stock:e.target.value})}/></label><label className="wide">Deskripsi<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="wide">Alias, pisahkan koma<input value={form.aliases} onChange={e=>setForm({...form,aliases:e.target.value})}/></label></div><button disabled={saving}>Kirim untuk moderasi</button></form><div className="seller-product-list">{products.map(product=>{const variant=product.product_variants?.find(v=>v.is_default);return <article key={product.id}>{product.image_url?<img src={product.image_url} alt={product.name}/>:<span>{product.emoji}</span>}<div><b>{product.name}</b><small>{variant?`${rupiah(variant.price)} / ${variant.unit} • stok ${variant.stock}`:'Varian belum ada'}</small><small>{(product.product_media||[]).filter(item=>item.media_type==='image').length} foto {(product.product_media||[]).some(item=>item.media_type==='video')?'• 🎬 video aktif':'• tanpa video'}</small><mark className={`status-${product.moderation_status}`}>{product.moderation_status}</mark></div>{variant&&<button disabled={saving} onClick={()=>openEdit(product)}>Edit produk</button>}</article>})}</div></section>}
 {tab==='orders'&&<section className="seller-orders">{!orders.length&&<div className="admin-empty">Belum ada pesanan untuk toko ini.</div>}{orders.map(order=><article key={order.id}><header><div><small>{order.orders?.order_number}</small><b>{new Date(order.created_at).toLocaleString('id-ID')}</b></div><mark className={`status-${order.status}`}>{order.status}</mark></header><p>{order.orders?.addresses?.recipient_name} • {order.orders?.addresses?.phone}<br/>{order.orders?.addresses?.address_text}</p><ul>{order.order_items?.map((item,index)=><li key={index}>{item.product_name} — {item.quantity} {item.variant_label} — {rupiah(item.line_total)}{item.note?` • ${item.note}`:''}</li>)}</ul><footer><b>Net: {rupiah(order.seller_net)}</b><div className="order-actions">{order.status==='pending'&&<button disabled={saving} onClick={()=>void saveOrderStatus(order,'confirmed')}>✓ Terima pesanan</button>}{order.status==='confirmed'&&<button disabled={saving} onClick={()=>void saveOrderStatus(order,'preparing')}>📦 Mulai siapkan</button>}{order.status==='preparing'&&<button disabled={saving} onClick={()=>void saveOrderStatus(order,'delivering')}>🚚 Siap diantar</button>}{order.status==='delivering'&&<button disabled={saving} onClick={()=>void saveOrderStatus(order,'completed')}>✅ Sudah diterima</button>}{['pending','confirmed','preparing'].includes(order.status)&&<button className="danger" disabled={saving} onClick={()=>void saveOrderStatus(order,'cancelled')}>Batalkan</button>}{['completed','cancelled'].includes(order.status)&&<span className="terminal-status">Status final</span>}</div></footer></article>)}</section>}
 {editingProduct&&<div className="seller-edit-overlay"><form className="seller-edit-modal" onSubmit={saveProductEdit}><button type="button" className="edit-close" onClick={()=>setEditingProduct(null)}>×</button><small>EDIT PRODUK</small><h2>{editingProduct.name}</h2><div className="edit-media"><div><b>Galeri saat ini / pengganti</b><span>Jika mengganti, pilih minimal 2 foto.</span></div><div className="media-previews">{editImagePreviews.map((url,index)=><img key={`${url}-${index}`} src={url} alt=""/>)}</div><label><input type="file" accept="image/*" multiple onChange={e=>chooseEditImages(e.target.files)}/>🖼️ Pilih galeri baru</label><label><input type="file" accept="video/mp4,video/webm" onChange={e=>chooseEditVideo(e.target.files?.[0]||null)}/>🎬 Ganti/tambah video</label>{editVideoPreview&&<video src={editVideoPreview} controls/>}</div><div className="seller-fields"><label>Nama<input value={editForm.name} onChange={e=>setEditForm({...editForm,name:e.target.value})}/></label><label>Emoji<input value={editForm.emoji} onChange={e=>setEditForm({...editForm,emoji:e.target.value})}/></label><label>Kategori<select value={editForm.category} onChange={e=>setEditForm({...editForm,category:e.target.value})}>{CATEGORIES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Satuan<input value={editForm.unit} onChange={e=>setEditForm({...editForm,unit:e.target.value})}/></label><label>Harga<input type="number" value={editForm.price} onChange={e=>setEditForm({...editForm,price:e.target.value})}/></label><label>Stok<input type="number" value={editForm.stock} onChange={e=>setEditForm({...editForm,stock:e.target.value})}/></label><label className="toggle-label"><input type="checkbox" checked={editForm.isActive} onChange={e=>setEditForm({...editForm,isActive:e.target.checked})}/> Produk aktif</label><label className="wide">Deskripsi<textarea value={editForm.description} onChange={e=>setEditForm({...editForm,description:e.target.value})}/></label><label className="wide">Alias<input value={editForm.aliases} onChange={e=>setEditForm({...editForm,aliases:e.target.value})}/></label></div><button className="save-edit" disabled={saving}>{saving?'Menyimpan...':'Simpan perubahan'}</button></form></div>}
 </div>}
