'use client';

import { FormEvent, useEffect, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/client';
import { rupiah } from '@/lib/format';

type Account={id:string;account_type:string;provider_name:string;account_name:string;account_number_masked:string;verification_status:string;verification_note?:string;is_primary:boolean};type Payout={id:string;payout_amount:number;gross_sales:number;platform_fee:number;adjustments:number;status:string;payout_reference?:string;requested_at?:string;paid_at?:string;created_at:string};type Data={store:{name:string};summary:{available:number;processing:number;paid:number;commission:number;minimumPayout:number};accounts:Account[];payouts:Payout[]};
export default function SellerFinance(){const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[showForm,setShowForm]=useState(false),[form,setForm]=useState({accountType:'bank',providerName:'',accountNumber:'',accountName:'',isPrimary:true});useEffect(()=>{void load()},[]);
 async function token(){const {data}=await getBrowserSupabase().auth.getSession();if(!data.session){location.href='/mitra/login?next=/mitra/keuangan';throw new Error('Login diperlukan')}return data.session.access_token}
 async function api(body?:any){const response=await fetch('/api/mitra/finance',{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Permintaan gagal');return result}
 async function load(){setLoading(true);setError('');try{setData(await api())}catch(reason){setError(reason instanceof Error?reason.message:'Gagal memuat')}finally{setLoading(false)}}
 async function addAccount(event:FormEvent){event.preventDefault();setSaving(true);setError('');try{await api({action:'add_account',...form});setNotice('Rekening ditambahkan dan menunggu verifikasi owner.');setShowForm(false);setForm({...form,providerName:'',accountNumber:'',accountName:''});await load()}catch(reason){setError(reason instanceof Error?reason.message:'Gagal menambah rekening')}finally{setSaving(false)}}
 async function deleteAccount(id:string){if(!confirm('Hapus rekening pending ini?'))return;await api({action:'delete_account',accountId:id});await load()}
 async function requestPayout(accountId:string){if(!confirm('Ajukan pencairan seluruh saldo tersedia?'))return;setSaving(true);setError('');try{await api({action:'request_payout',accountId});setNotice('Permintaan pencairan dikirim ke owner.');await load()}catch(reason){setError(reason instanceof Error?reason.message:'Pencairan gagal')}finally{setSaving(false)}}
 if(loading)return<div className="dashboard-loading">Memuat keuangan...</div>;if(!data)return<div className="form-alert error">{error}</div>;const verified=data.accounts.find(a=>a.verification_status==='verified');
 return <main className="finance-page"><header><a href="/mitra/dashboard">←</a><div><small>KEUANGAN MITRA</small><h1>{data.store.name}</h1></div></header>{error&&<div className="form-alert error">{error}</div>}{notice&&<div className="form-alert success">{notice}</div>}<section className="balance-card"><small>SALDO TERSEDIA</small><h2>{rupiah(data.summary.available)}</h2><p>Dari order completed yang belum masuk payout.</p><button disabled={saving||!verified||data.summary.available<data.summary.minimumPayout} onClick={()=>verified&&void requestPayout(verified.id)}>Ajukan pencairan</button>{!verified&&<em>Tambahkan rekening dan tunggu verifikasi owner.</em>}{data.summary.available<data.summary.minimumPayout&&<em>Minimum pencairan {rupiah(data.summary.minimumPayout)}.</em>}</section><section className="finance-metrics"><article><span>⏳</span><b>{rupiah(data.summary.processing)}</b><small>Potensi dari order berjalan</small></article><article><span>✅</span><b>{rupiah(data.summary.paid)}</b><small>Sudah dicairkan</small></article><article><span>🏷️</span><b>{rupiah(data.summary.commission)}</b><small>Total komisi platform</small></article></section>
 <section className="payment-accounts"><header><div><h2>Rekening pencairan</h2><p>Nomor rekening hanya ditampilkan dalam bentuk tersamarkan.</p></div><button onClick={()=>setShowForm(!showForm)}>+ Tambah</button></header>{showForm&&<form onSubmit={addAccount}><select value={form.accountType} onChange={e=>setForm({...form,accountType:e.target.value})}><option value="bank">Bank</option><option value="ewallet">E-wallet</option></select><input placeholder="Nama bank/e-wallet" value={form.providerName} onChange={e=>setForm({...form,providerName:e.target.value})}/><input placeholder="Nomor rekening/akun" value={form.accountNumber} onChange={e=>setForm({...form,accountNumber:e.target.value})}/><input placeholder="Nama pemilik" value={form.accountName} onChange={e=>setForm({...form,accountName:e.target.value})}/><button disabled={saving}>Simpan rekening</button></form>}<div className="account-list-finance">{!data.accounts.length&&<p>Belum ada rekening.</p>}{data.accounts.map(account=><article key={account.id}><div><b>{account.provider_name} • {account.account_number_masked}</b><span>{account.account_name}</span></div><mark className={`verify-${account.verification_status}`}>{account.verification_status}</mark>{account.verification_status==='verified'&&<button disabled={saving||data.summary.available<data.summary.minimumPayout} onClick={()=>void requestPayout(account.id)}>Cairkan</button>}{account.verification_status==='pending'&&<button onClick={()=>void deleteAccount(account.id)}>Hapus</button>}</article>)}</div></section>
 <section className="payout-history"><h2>Riwayat pencairan</h2>{!data.payouts.length&&<p>Belum ada pencairan.</p>}{data.payouts.map(payout=><article key={payout.id}><div><b>{rupiah(payout.payout_amount)}</b><span>{new Date(payout.created_at).toLocaleString('id-ID')}</span></div><mark className={`payout-${payout.status}`}>{payout.status}</mark><small>Gross {rupiah(payout.gross_sales)} • Komisi {rupiah(payout.platform_fee)}</small></article>)}</section></main>
}
