'use client';

import { FormEvent, useEffect, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/client';
import { rupiah } from '@/lib/format';

const DAYS=[['monday','Senin'],['tuesday','Selasa'],['wednesday','Rabu'],['thursday','Kamis'],['friday','Jumat'],['saturday','Sabtu'],['sunday','Minggu']];
type Day={open:boolean;from:string;to:string};type Store={id:string;name:string;slug:string;description:string;phone:string;whatsapp:string;address_text:string;logo_url?:string;banner_url?:string;opening_hours:Record<string,Day>;min_order:number;preparation_minutes:number;delivery_area_text?:string;is_accepting_orders:boolean;temporary_close_reason?:string;vacation_until?:string;order_cutoff_time?:string};

export default function StoreSettings(){const [store,setStore]=useState<Store|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[logoFile,setLogoFile]=useState<File|null>(null),[bannerFile,setBannerFile]=useState<File|null>(null),[logoPreview,setLogoPreview]=useState(''),[bannerPreview,setBannerPreview]=useState('');useEffect(()=>{void load()},[]);
 async function token(){const {data}=await getBrowserSupabase().auth.getSession();if(!data.session){location.href='/mitra/login?next=/mitra/pengaturan';throw new Error('Login diperlukan')}return data.session.access_token}
 async function load(){setLoading(true);try{const response=await fetch('/api/mitra/store',{headers:{Authorization:`Bearer ${await token()}`}});const data=await response.json();if(!response.ok)throw new Error(data.error);setStore(data.store);setLogoPreview(data.store.logo_url||'');setBannerPreview(data.store.banner_url||'');}catch(reason){setError(reason instanceof Error?reason.message:'Gagal memuat toko')}finally{setLoading(false)}}
 function selectAsset(file:File|null,type:'logo'|'banner'){setError('');if(!file)return;if(!file.type.startsWith('image/')||file.size>5*1024*1024){setError('Logo/banner harus gambar dan maksimal 5 MB.');return;}const url=URL.createObjectURL(file);if(type==='logo'){setLogoFile(file);setLogoPreview(url)}else{setBannerFile(file);setBannerPreview(url)}}
 async function upload(file:File,userId:string,label:string){const supabase=getBrowserSupabase();const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'');const path=`${userId}/${label}-${Date.now()}.${ext}`;const {error:e}=await supabase.storage.from('store-assets').upload(path,file,{upsert:false});if(e)throw e;return supabase.storage.from('store-assets').getPublicUrl(path).data.publicUrl}
 function day(key:string){return store?.opening_hours?.[key]||{open:true,from:'07:00',to:'18:00'}}
 function updateDay(key:string,value:Partial<Day>){if(!store)return;setStore({...store,opening_hours:{...store.opening_hours,[key]:{...day(key),...value}}})}
 async function save(event:FormEvent){event.preventDefault();if(!store)return;setSaving(true);setError('');setNotice('');try{const supabase=getBrowserSupabase();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error('Login diperlukan');let logo=store.logo_url||'',banner=store.banner_url||'';if(logoFile)logo=await upload(logoFile,user.id,'logo');if(bannerFile)banner=await upload(bannerFile,user.id,'banner');const response=await fetch('/api/mitra/store',{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await token()}`},body:JSON.stringify({...store,logo_url:logo,banner_url:banner})});const data=await response.json();if(!response.ok)throw new Error(data.error);setStore(data.store);setLogoFile(null);setBannerFile(null);setNotice('Pengaturan toko berhasil disimpan.');}catch(reason){setError(reason instanceof Error?reason.message:'Gagal menyimpan')}finally{setSaving(false)}}
 if(loading)return<div className="dashboard-loading">Memuat pengaturan...</div>;if(!store)return<div className="form-alert error">{error||'Toko tidak ditemukan.'}</div>;
 return <main className="store-settings-page"><header><a href="/mitra/dashboard">←</a><div><small>PENGATURAN TOKO</small><h1>{store.name}</h1></div><a href={`/toko/${store.slug}`}>Lihat toko ↗</a></header>{error&&<div className="form-alert error">{error}</div>}{notice&&<div className="form-alert success">{notice}</div>}<form onSubmit={save}>
 <section className="store-assets"><label><span>Logo toko</span><input type="file" accept="image/*" onChange={e=>selectAsset(e.target.files?.[0]||null,'logo')}/>{logoPreview?<img className="logo-preview" src={logoPreview} alt="Logo"/>:<i>🏪</i>}</label><label><span>Banner toko</span><input type="file" accept="image/*" onChange={e=>selectAsset(e.target.files?.[0]||null,'banner')}/>{bannerPreview?<img className="banner-preview" src={bannerPreview} alt="Banner"/>:<i>🖼️</i>}</label></section>
 <section className="settings-card"><h2>Profil toko</h2><div className="settings-grid"><label>Nama toko<input value={store.name} onChange={e=>setStore({...store,name:e.target.value})}/></label><label>WhatsApp<input value={store.whatsapp||''} onChange={e=>setStore({...store,whatsapp:e.target.value})}/></label><label className="wide">Deskripsi<textarea value={store.description||''} onChange={e=>setStore({...store,description:e.target.value})}/></label><label className="wide">Alamat toko<textarea value={store.address_text} onChange={e=>setStore({...store,address_text:e.target.value})}/></label><label className="wide">Area layanan<input value={store.delivery_area_text||''} onChange={e=>setStore({...store,delivery_area_text:e.target.value})} placeholder="Kaur Selatan dan sekitarnya"/></label></div></section>
 <section className="settings-card"><h2>Operasional</h2><label className="accept-orders"><input type="checkbox" checked={store.is_accepting_orders} onChange={e=>setStore({...store,is_accepting_orders:e.target.checked})}/><div><b>{store.is_accepting_orders?'Toko menerima order':'Toko tutup sementara'}</b><span>Pelanggan melihat status ini di halaman toko.</span></div></label>{!store.is_accepting_orders&&<label>Alasan tutup<input value={store.temporary_close_reason||''} onChange={e=>setStore({...store,temporary_close_reason:e.target.value})} placeholder="Contoh: stok sedang diperbarui"/></label>}<div className="settings-grid"><label>Minimum order<input type="number" value={store.min_order} onChange={e=>setStore({...store,min_order:Number(e.target.value)})}/><small>{rupiah(store.min_order||0)}</small></label><label>Waktu persiapan (menit)<input type="number" min="5" max="1440" value={store.preparation_minutes} onChange={e=>setStore({...store,preparation_minutes:Number(e.target.value)})}/></label><label>Batas order harian<input type="time" value={store.order_cutoff_time||''} onChange={e=>setStore({...store,order_cutoff_time:e.target.value})}/></label><label>Libur sampai<input type="datetime-local" value={store.vacation_until?.slice(0,16)||''} onChange={e=>setStore({...store,vacation_until:e.target.value?new Date(e.target.value).toISOString():''})}/></label></div></section>
 <section className="settings-card"><h2>Jam buka</h2><div className="opening-hours">{DAYS.map(([key,label])=><article key={key}><label><input type="checkbox" checked={day(key).open} onChange={e=>updateDay(key,{open:e.target.checked})}/><b>{label}</b></label><input type="time" disabled={!day(key).open} value={day(key).from} onChange={e=>updateDay(key,{from:e.target.value})}/><span>–</span><input type="time" disabled={!day(key).open} value={day(key).to} onChange={e=>updateDay(key,{to:e.target.value})}/></article>)}</div></section>
 <button className="save-store-settings" disabled={saving}>{saving?'Menyimpan...':'Simpan pengaturan toko'}</button>
 </form></main>
}
